### ISSUE TITLE
Styling Hompage

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#12]
## Value Proposition

As a User I want to have a better styling
so that it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117982616/219028372-dae66be6-5569-40df-b6ce-666211c71c1f.png)

## Acceptance Criteria

- [ ] show styled input fields
- [ ] show styled radiobuttons 
- [ ] show styled card
      ​

## Tasks

- [ ] add styling to hompage button 
- [ ] add styling to dashboard button
- [ ] add styling to input fields​

## Complexity

M
