### ISSUE TITLE
Styling Dashboard

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#13]
## Value Proposition

As a User I want to have a better UI
so that it's easier to understand the app.
​

## Description

![image](https://user-images.githubusercontent.com/117982616/219032296-1d22d19d-5473-4dea-9148-b8245460f093.png)
​

## Acceptance Criteria

- [ ] display card with the result
- [ ] show card for the saved flights
- [ ] show styled button to save 
- [ ] show a styled button to delete 

## Tasks

- [ ] add styling to the cards
- [ ] add a styling to save
- [ ] add a styling to delete

      ​

## Complexity

M
