### ISSUE TITLE
List items with radio buttons

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#2]
## Value Proposition

As a user I want a button for each filter and a button to confirm the input, 
so that my entries are evaluated

​

## Description

![image](https://user-images.githubusercontent.com/117982616/214043569-81c89ec4-2bcc-42de-b793-a7ff6b33746b.png)

## Acceptance Criteria

- [ ] filters to confirm with button are displayed 
- [ ] filters are displayed in two categories 
- [ ] type of flight
- [ ] type of flight class
​

## Tasks

- [ ] create a list with five entries 
- [ ] create a selection button for each list entry
- [ ] add a button with a link that leads to Results.js​

## Complexity

S

**Comment by AGeck113** [comment]
Hi Diren, looks good to me.
Could you be more specific here? Something like:
-filters are displayed in two categories  (how do you want to show them? li/card/ something else?)
-(One with the) type of flight 
- (One with the) type of flight class

**Comment by Diren-T** [comment]
Hi @AGeck113 , thanks for your feedback. The red frame is used to indicate what is meant.  
- the type of flight
- the flight class 
both are on the same card. Does this solve your comment?

**Comment by JohannesMisch** [comment]
Hey Diren, great user story. 👍
