### ISSUE TITLE
Navigation dashboard and IATA-code implmentation 

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#3]
## Value Proposition

As a user, I want to have a button that takes me to the dashboard page, 
and the ability to find the airport codes so I can see the results
​

## Description

![image](https://user-images.githubusercontent.com/117982616/214270053-1cfec13a-bdd6-4425-a1f3-005e8274c2f5.png)
​

## Acceptance Criteria

- [ ] a button on the bottom left, links to dashboard.js page
- [ ] logo from IATA on the top right, linking to 
https://www.iata.org/en/publications/directories/code-search/

      ​

## Tasks

- [ ] use a link component from react router
- [ ] navigate the user to Dashobard.js when the button is clicked 
- [ ] create a confirmation prompt before the IATA logo opens a new page in React​

## Complexity

M

**Comment by RobinWitt** [comment]
where and how are the flights saved? in a database, local, or just temporarily?

**Comment by RobinWitt** [comment]
perfect!
