### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#4]
## Value Proposition

As a user, I want to be able to see my results on the map so that I have an overview of my results.
​

## Description

![image](https://user-images.githubusercontent.com/117982616/214325408-f5cc9270-39ed-487f-84aa-5162a2e4c58a.png)

## Acceptance Criteria

- [ ] Describe every scenarios in detail
- [ ] e.g. Aall inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by marcterre** [comment]
Hey Diren, i get that you implement a header but in your wireframe im not sure what exactly the boxes inside your header should present? I guess they are for the home button and a logo but can you display it more detailed? 
You could also write it more detailed in your acceptance criteria like: "There is a header with a Link which leads to the homepage and a Logo... " Same with your navigation. Also a Link to your homepage should do it. 🙂

**Comment by Diren-T** [comment]
thanks @marcterre i have updated this

**Comment by JoergWolff** [comment]
LGTM
