### ISSUE TITLE
Dahsboard implementation

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#6]
## Value Proposition

As a user I want to have a button so that my input is submitted and displayed
​
​

## Description

![image](https://user-images.githubusercontent.com/117982616/216347652-aaca3716-cc1d-4fea-a0cf-ebede51ecb86.png)
​

## Acceptance Criteria

- [ ] there is a button to confirm the input
- [ ] the result will be displayed on the flights page
      ​

## Tasks

- [ ] create a link to the flights page
- [ ] create a component with FlightCO2Results​

## Complexity

S

**Comment by AstridOttmann** [comment]
Looks good to me!
Maybe you can become a little more concrete in your tasks: what do you fetch? Where is the fetched data displayed?

I find it a little bit confusing, that you have a plus on your button. That implicates, that the result is added to something, but when I get it right it is only the result of the last flight.

**Comment by magjo21** [comment]
Hi Diren,
looks good already.
Do I see correctly that you have 2 times "complexity" and 2 times "tasks" in your US?
Then I would suggest to combine the tasks and write the one part of the complexity in your AC. 
(there is a button to confirm the input
 the result is displayed on the flight page
 the return value is stored in a variable)
