### ISSUE TITLE
Delete Function

### ISSUE THREAD

**Issue by Diren-T** [Diren-T/capstone-project#7]
## Value Proposition

as a user, i want to delete my saved entries so that i can sort out my list
​

## Description

![image](https://user-images.githubusercontent.com/117982616/216355836-9f283c43-25aa-4dba-972c-4463db70022d.png)
​

## Acceptance Criteria

- [ ] for each list entry a delete button is displayed.
- [ ] if the delete button is clicked, the list entry will be removed from the list

      ​

## Tasks

- [ ] create a delete button
- [ ] write a handleRemove function to delete the entry from the list
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by RobinWitt** [comment]
In this user story, you should also specify in the "tasks" where the entries are saved (and deleted from)
